Repository IEEE-VIT/ToDo-iOS, pull requests merged in 2020-10, with the labels that each got.

#14 Added Delete task functionality
  Application/To-Do.xcodeproj/project.xcworkspace/xcuserdata/harshitparikh.xcuserdatad/UserInterfaceState.xcuserstate
  Application/To-Do/Controller/TodoViewController.swift
Labels: category: documentation, status: changes-requested

#13 Added due date label for each task
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
Labels: hacktoberfest, status: changes-requested

#33 Add Star/Unstar feature
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do.xcodeproj/xcshareddata/xcschemes/To-Do.xcscheme
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/View/Base.lproj/Main.storyboard
  Application/To-Do/View/TaskCell.swift
Labels: hacktoberfest, status: changes-requested

#34 Feat: use core-data to store the ToDo list. #21
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/Model/Tasks Model.swift
  Application/To-Do/Model/To_Do.xcdatamodeld/To_Do.xcdatamodel/contents
Labels: status: on-hold

#30 Adding Dismiss Keyboard on Tap
  Application/To-Do/Controller/TaskDetailsViewController.swift
Labels: status: changes-requested

#35 Added task sort feature
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/Model/SortTypes.swift
  Application/To-Do/Model/To_Do.xcdatamodeld/To_Do.xcdatamodel/contents
  Application/To-Do/View/Base.lproj/Main.storyboard
Labels: Hacktoberfest-accepted, status: needs-review

#43 Add validations for creating a task
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Helpers/Alert.swift
Labels: Hacktoberfest-accepted, status: needs-review, type: bug

#44 Add Onboarding screen
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/OnboardingViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/View/Base.lproj/Main.storyboard
Labels: Hacktoberfest-accepted, category: user-interface, status: needs-testing, type: enhancement

#50 Added a launch screen
  Application/To-Do/View/Base.lproj/LaunchScreen.storyboard
Labels: Hacktoberfest-accepted, category: storyboard, category: user-interface

#49 Add tests targets and sample core data test
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do.xcodeproj/xcshareddata/xcschemes/To-Do.xcscheme
  Application/To-DoTests/Info.plist
  Application/To-DoTests/TaskTests.swift
Labels: Hacktoberfest-accepted, status: needs-review, type: testing

#53 Placeholder texts added for textfields
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/View/Base.lproj/Main.storyboard
Labels: Hacktoberfest-accepted, status: changes-requested, type: maintenance

#62 Feature/empty todo list state
  Application/To-Do/Controller/TodoViewController.swift
Labels: Hacktoberfest-accepted, status: needs-review

#64 Add empty fetch result state (#57)
  Application/To-Do/Controller/ResultsTableController.swift
Labels: category: coding, category: user-experience, status: changes-requested, status: needs-testing

#63 Adding empty state if no tasks added
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/ResultsTableController.swift
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/Helpers/EmptyState.swift
Labels: status: on-hold

#61 Create a Task History Tab
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Controller/TaskHistoryViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/Model/To_Do.xcdatamodeld/To_Do2.xcdatamodel/contents
  Application/To-Do/View/Base.lproj/Main.storyboard
  Application/To-DoTests/TaskTests.swift
Labels: Hacktoberfest-accepted, category: user-experience, status: needs-review

#67 refactor + comment code.
  Application/To-Do.xcodeproj/project.pbxproj
  Application/To-Do/Controller/OnboardingViewController.swift
  Application/To-Do/Controller/ResultsTableController.swift
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Controller/TaskHistoryViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
  Application/To-Do/Helpers/Constants.swift
  Application/To-Do/View/Cells/ImageAttachmentCell.swift
  Application/To-Do/View/Cells/TaskCell.swift
  Application/To-Do/View/EmptyState.swift
Labels: Hacktoberfest-accepted, category: coding, category: documentation, type: maintenance

#77 Add history empty view
  Application/To-Do/Controller/TaskHistoryViewController.swift
  Application/To-Do/View/EmptyState.swift
Labels: Hacktoberfest-accepted, category: user-experience, status: changes-requested

#87 Adds haptics to TasksDetails and TodoViewController
  Application/To-Do/Controller/TaskDetailsViewController.swift
  Application/To-Do/Controller/TodoViewController.swift
Labels: Hacktoberfest-accepted
